import Head from "next/head";
import { useState } from "react";

export default function Home({ users }) {
  const [name, setName] = useState("");
  const [foundUsers, setFoundUsers] = useState(users);

  const filter = (e) => {
    const keyword = e.target.value;

    if (keyword !== "") {
      const results = users.filter((user) => {
        return user.name.toLowerCase().startsWith(keyword.toLowerCase());
      });
      setFoundUsers(results);
    } else {
      setFoundUsers(users);
    }

    setName(keyword);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input className="border" onChange={filter} type="search" value={name} />

      <div>
        {foundUsers && foundUsers.length > 0 ? (
          foundUsers.map((user) => <h1>{user.name}</h1>)
        ) : (
          <h1>No results found!</h1>
        )}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json();

  return {
    props: {
      users: data,
    },
  };
}
